### ISSUE TITLE
Archive fails to start with Connection Refused to db

### ISSUE THREAD

**Issue by petrkalina** [j4care/installer-issues#41]
- the wait for DB on container startup succeeds
```
h5waz  Waiting for ldap:636 ...
h5waz  done
h5waz  Waiting for db:5432 ...
h5waz  done
h5waz  Waiting for test-elk.lan.j4care.com:8514 ...
h5waz  done
h5waz  Waiting for keycloak:8843 ...
h5waz  done
h5waz  Starting Wildfly 26.1.2.Final
```
- the archive fails to start with
```
2023-07-05 11:19:24,475 INFO  [org.jboss.as.jpa] (ServerService Thread Pool -- 81) WFLYJPA0010: Starting Persistence Unit (phase 2 of 2) Service 'j4dcm4chee-arc-ear-5.31.0-psql-secure.ear#dcm4chee-arc'
2023-07-05 11:19:24,517 INFO  [org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean] (MSC service thread 1-2) Creating Service {urn:ihe:rad:xdsi-b:2009}ImagingDocumentSource from WSDL: /wsdl/XDS-I.b_ImagingDocumentSource.wsdl
2023-07-05 11:19:24,587 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (ServerService Thread Pool -- 81) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: IJ031084: U
nable to create connection
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:364)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:371)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:13
...
Caused by: org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql@42.4.1//org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
        at org.postgresql@42.4.1//org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql@42.4.1//org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
        at org.postgresql@42.4.1//org.postgresql.Driver.makeConnection(Driver.java:434)
        at org.postgresql@42.4.1//org.postgresql.Driver.connect(Driver.java:291)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:335)
        ... 39 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.postgresql@42.4.1//org.postgresql.core.PGStream.createSocket(PGStream.java:241)
        at org.postgresql@42.4.1//org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql@42.4.1//org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
        at org.postgresql@42.4.1//org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
        ... 44 more
```

the key aspect is that the problem does not occur all the time - after next restart it may not occur.. Occurs on multiple docker versions and multiple archive versions.

prectical resolution i.e.

```

  arc:
...
    extra_hosts:
      - "db:172.25.217.10"
```

**Comment by petrkalina** [comment]
- may be related to docker DNS on overlay network
- may be related to removing dnsrr mode from templates - try setting dnsrr set on DB service?

**Comment by gunterze** [comment]
would rather expect 
```
java.net.UnknownHostException: db
```
and not
```
java.net.ConnectException: Connection refused
```
if there is an issue with the docker DNS.

Does the issue remains after forcing a redeployment by 
```console
$ sudo touch <path-to-host-mounted-/opt/wildfly/standalone>/deployments/j4dcm4chee-arc-ear-VERSION-psql-secure.ear
```
?
Perhaps, the DB is not yet ready - particularly when the DB get initialized on first startup - when
```bash
nc -w 1 -z db 5432
```
already succeeds. ( https://github.com/dcm4che-dockerfiles/wildfly/blob/master/docker-entrypoint.sh#L73 )

**Comment by j4care-christianhahn** [comment]
issue is still here and the db was for sure ready as it also happens if I just restart the archive container. what was the reason of removing dnsrr ?
